version: '2'

services:
  jira:
    image: openkunlun/jira
    container_name: jira
    ports:
      - '3080:8080'
    volumes:
      - /opt/atlassian/jira/:/opt/atlassian/jira/
  postgresql:
    image: postgres
    container_name: wiki_postgres
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=openkunlun'
      - 'POSTGRES_PASSWORD=#a1a4*6DK'
      - 'POSTGRES_DB=kunlunjira'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    volumes:
      - /root/docker-volume/wiki_postgres/data/:/var/lib/postgresql/data/
